/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api/v1/db-ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_dbPing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Basic health payload */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** ヘルスチェック用 HEAD（200 No Content） */
        head: operations["HealthController_head"];
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe（プロセス稼働判定） */
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe（依存疎通: DB） */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/debug-sentry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sentry エラー送信のデバッグ（保護付き）
         * @description SENTRY_DEBUG_ENABLED=1 の環境でのみエラーを投げて Sentry に送る。その他は 404。
         */
        get: operations["HealthController_debugSentry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** パスワード再設定トークンの発行 */
        post: operations["PasswordController_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 再設定トークンの消費（パスワード変更） */
        post: operations["PasswordController_consume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 応募一覧 */
        get: operations["ApplicationsController_list"];
        put?: never;
        /** 応募の一次受付を登録 */
        post: operations["ApplicationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 応募詳細の取得（面談票・添付含む） */
        get: operations["ApplicationsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 応募を承認し、Cast を自動作成/更新
         * @description status=approved にしつつ、Application 内容から users/casts/属性/嗜好/背景を作成（既存があれば再利用）。承認後は Cast を正として Application の未入力�目を補完。
         */
        patch: operations["ApplicationsController_approve"];
        trace?: never;
    };
    "/api/v1/applications/{id}/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 面接票（登録用紙）を取り込み・更新 */
        patch: operations["ApplicationsController_upsertInterviewForm"];
        trace?: never;
    };
    "/api/v1/applications/{id}/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 応募にファイルメタ情�を添付（身分証/自撮り/登録用紙など） */
        post: operations["ApplicationsController_createDoc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}/migrate-to-cast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 応募データを Cast に移行（User/Cast/付随テーブルを生成）
         * @description Application の内容をもとに users/casts/... を作成（デバッグ用）
         */
        post: operations["ApplicationsController_migrateToCast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casts/issue-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** cast_codeを採番しCastへ付与（冪等） */
        post: operations["CastCodeController_issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 店舗一覧（キーワード付き） */
        get: operations["ShopsController_list"];
        put?: never;
        /** 店舗作成（番号は自動採番／キーワードまとめて作成） */
        post: operations["ShopsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 店舗詳細（reqKeywords を同梱） */
        get: operations["ShopsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 店舗更新（reqKeywords 全入替） */
        patch: operations["ShopsController_update"];
        trace?: never;
    };
    "/api/v1/people/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PeopleController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["PeopleController_updatePartial"];
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LocationsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LocationsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["LocationsController_update"];
        trace?: never;
    };
    "/api/v1/shops/{shopId}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RequirementsController_get"];
        put: operations["RequirementsController_upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{shopId}/fixed-casts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FixedCastsController_list"];
        put?: never;
        post: operations["FixedCastsController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{shopId}/fixed-casts/{castId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["FixedCastsController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{shopId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AssignmentsController_list"];
        put?: never;
        post: operations["AssignmentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{shopId}/assignments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AssignmentsController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ResetIssueDto: Record<string, never>;
        IssueResetSuccessDto: {
            /** @example true */
            ok: boolean;
            /**
             * @example email
             * @enum {string}
             */
            channel: "email" | "line";
            /** @example URL-safe-base64-token */
            token: string;
        };
        CooldownErrorDto: {
            /** @example 429 */
            statusCode: number;
            /** @example 短時間に複数回リクエストが行われました。しばらく待ってから再度お試しく�さい。 */
            message: string;
            /**
             * @description クールダウン残り秒（返らない�合もあるため optional）
             * @example 96
             */
            remainingSec?: number;
        };
        ResetConsumeDto: Record<string, never>;
        ConsumeResultDto: {
            /** @example true */
            ok: boolean;
        };
        CreateApplicationDto: {
            /**
             * @example line
             * @enum {string}
             */
            channel: "line" | "web" | "other";
            /** @example user@example.com */
            email?: string;
            /** @example +81-90-1234-5678 */
            phone?: string;
            /** @example 山田 花子 */
            fullName?: string;
            /** @example true */
            drinkOk?: boolean;
            /**
             * @example [
             *       "ガールズバー",
             *       "スナック"
             *     ]
             */
            genres?: string[];
            /**
             * @description 希望時給(円)
             * @example 2500
             */
            hourlyExpectation?: number;
        };
        UpsertInterviewFormDto: Record<string, never>;
        CreateApplicationDocDto: Record<string, never>;
        CastAttributeEntity: {
            /**
             * @description 身長(cm)
             * @example 160
             */
            heightCm?: Record<string, never>;
            /**
             * @description 服サイズ（例: XS/S/M/L/XL など）
             * @example M
             */
            clothingSize?: Record<string, never>;
            /**
             * @description 靴サイズ(cm)
             * @example 24.5
             */
            shoeSizeCm?: Record<string, never>;
            /** @description タトゥー有無 */
            tattoo?: Record<string, never>;
            /** @description 送迎が必要か */
            needPickup?: Record<string, never>;
        };
        CastPreferenceEntity: {
            /**
             * @description 希望時給
             * @example 2500
             */
            desiredHourly?: Record<string, never>;
            /**
             * @description 希望月収
             * @example 250000
             */
            desiredMonthly?: Record<string, never>;
            /**
             * @description 希望曜日 CSV
             * @example Mon,Wed,Fri
             */
            preferredDays?: Record<string, never>;
            /**
             * @description 希望時間帯 例: 18:00-23:00
             * @example 18:00-23:00
             */
            preferredTimeBand?: Record<string, never>;
            /**
             * @description 希望エリア
             * @example 渋谷
             */
            preferredArea?: Record<string, never>;
            /** @description NG店舗メモ */
            ngShopNotes?: Record<string, never> | null;
            /** @description 備考 */
            notes?: Record<string, never> | null;
        };
        CastBackgroundEntity: {
            /**
             * @description 認知経路
             * @example HP
             */
            howFound?: Record<string, never>;
            /**
             * @description 応募動機
             * @example 稼ぎたい
             */
            motivation?: Record<string, never>;
            /**
             * @description 他社(他エージェンシー)数
             * @example 1〜3社
             */
            otherAgencies?: Record<string, never>;
            /**
             * @description 選定理由
             * @example サポート
             */
            reasonChoose?: Record<string, never>;
            /**
             * @description 店舗選定ポイント
             * @example 時給・立地
             */
            shopSelectionPoints?: Record<string, never>;
        };
        CastNgItemEntity: {
            /**
             * Format: uuid
             * @description NG店の shopId
             */
            shopId: string;
            /** @description NG登録のソース例: 'cast' | 'staff' */
            source?: string;
            /** @description 理由 */
            reason?: string;
            /**
             * @description 登録日時(ISO8601)
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        CastEntity: {
            /**
             * Format: uuid
             * @description ユーザーID（Cast主キー）
             */
            userId: string;
            /**
             * @description 4桁の管理番号（UNIQUE／0001〜9999、ゼロ埋め）
             * @example 0123
             */
            managementNumber?: string | null;
            /**
             * @description 表示名
             * @example 山田花子
             */
            displayName?: Record<string, never>;
            /**
             * @description 生年月日(ISO8601)
             * @example 2000-01-01
             */
            birthdate?: Record<string, never>;
            /**
             * @description 年齢(サーバ側計算でも可)
             * @example 24
             */
            age?: Record<string, never>;
            /**
             * @description 住所
             * @example 東京都渋谷区
             */
            address?: Record<string, never>;
            /**
             * @description 電話番号
             * @example +81-90-1234-5678
             */
            phone?: Record<string, never>;
            /**
             * @description メール
             * @example sample@example.com
             */
            email?: Record<string, never>;
            /** @description 飲酒可否 */
            drinkOk?: Record<string, never>;
            /** @description 経験有無 */
            hasExperience?: Record<string, never>;
            /**
             * @description プロフィール写真URL
             * @example https://...
             */
            profilePhotoUrl?: Record<string, never>;
            /** @description 備考 */
            note?: Record<string, never> | null;
            /** @description 属性（最新行が先頭想定） */
            attributes?: components["schemas"]["CastAttributeEntity"][] | null;
            /** @description 希望（最新行が先頭想定） */
            preferences?: components["schemas"]["CastPreferenceEntity"][] | null;
            /** @description 背景（最新行が先頭想定） */
            backgrounds?: components["schemas"]["CastBackgroundEntity"][] | null;
            ngs: components["schemas"]["CastNgItemEntity"][];
            /**
             * @description 作成日時(ISO8601)
             * @example 2025-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * @description 更新日時(ISO8601)
             * @example 2025-01-02T12:34:56.000Z
             */
            updatedAt?: Record<string, never>;
        };
        IssueCastCodeResponseDto: Record<string, never>;
        IssueCastCodeDto: Record<string, never>;
        ShopEntity: {
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * @description 呼出番号（3〜4桁、先頭ゼロ許容）
             * @example 0123
             */
            shopNumber?: Record<string, never> | null;
            prefecture?: Record<string, never>;
            city?: Record<string, never>;
            addressLine?: Record<string, never>;
            phone?: Record<string, never>;
            genre?: Record<string, never>;
            createdAt: string;
            updatedAt: string;
        };
        CreateShopDto: {
            /** @description 店舗名 */
            name: string;
            /**
             * @description 呼出番号（3〜4桁、先頭ゼロ許容）
             * @example 0123
             */
            shopNumber?: string | null;
            /**
             * @description 都道府県
             * @example 福岡県
             */
            prefecture?: string | null;
            /**
             * @description 市区町村
             * @example 福岡市
             */
            city?: string | null;
            /**
             * @description 住所（番地以降）
             * @example 中央区天神1-1-1
             */
            addressLine?: string | null;
            /**
             * @description 電話番号
             * @example 092-000-0000
             */
            phone?: string | null;
            /**
             * @description 業態/ジャンル
             * @example ラウンジ
             */
            genre?: string | null;
            /**
             * @description 要望キーワード（まとめて登録、最大20件）
             * @example [
             *       "未経験歓迎",
             *       "送迎あり"
             *     ]
             */
            reqKeywords?: string[] | null;
        };
        UpdateShopDto: {
            /**
             * @description 店舗名
             * @example Tiara 天神店
             */
            name?: string | null;
            /**
             * @description 呼出番号（3〜4桁、先頭ゼロ許容）
             * @example 0123
             */
            shopNumber?: string | null;
            /**
             * @description 都道府県
             * @example 福岡県
             */
            prefecture?: string | null;
            /**
             * @description 市区町村
             * @example 福岡市
             */
            city?: string | null;
            /**
             * @description 住所（番地以降）
             * @example 中央区天神1-1-1
             */
            addressLine?: string | null;
            /**
             * @description 電話番号
             * @example 092-000-0000
             */
            phone?: string | null;
            /**
             * @description 業態/ジャンル
             * @example ラウンジ
             */
            genre?: string | null;
            /**
             * @description 要望キーワード（全入替・最大20件）
             * @example [
             *       "未経験歓迎",
             *       "送迎あり"
             *     ]
             */
            reqKeywords?: string[] | null;
        };
        ListAssignmentsDto: {
            /**
             * @description 単日指定（互換）YYYY-MM-DD。与えた�合は from/to に展開されます
             * @example 2025-11-03
             */
            date?: string;
            /**
             * @description 開始時刻の下限（含む・ISO8601）
             * @example 2025-11-03T00:00:00Z
             */
            from?: string;
            /**
             * @description 開始時刻の上限（未満・ISO8601）
             * @example 2025-11-04T00:00:00Z
             */
            to?: string;
            /**
             * @description ステータス（複数指定可: CSV または ?status=... を複数）
             * @example planned,assigned
             */
            status?: ("planned" | "assigned" | "working" | "completed" | "cancelled")[];
            /** @description キャストIDで絞り込み */
            castId?: string;
            /**
             * @description 取得件数（最大200）
             * @default 50
             * @example 50
             */
            take: number;
            /** @description カーソルID（ページング） */
            cursor?: string;
            /**
             * @description 開始時刻の並び�
             * @default asc
             * @enum {string}
             */
            order: "asc" | "desc";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    AppController_dbPing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description アプリの基本的な稼働情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    HealthController_head: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 常に { ok: true, ts } を返す簡易生存確認 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DB 疎通に成功すれば { ready: true }、失敗時は { ready: false } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    HealthController_debugSentry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sentry デバッグが無効 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PasswordController_reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetIssueDto"];
            };
        };
        responses: {
            /** @description 成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueResetSuccessDto"];
                };
            };
            /** @description クールダウン中 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CooldownErrorDto"];
                };
            };
        };
    };
    PasswordController_consume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetConsumeDto"];
            };
        };
        responses: {
            /** @description 結果（ok=true: 成功 / ok=false: トークン無効・再利用など） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumeResultDto"];
                };
            };
        };
    };
    ApplicationsController_list: {
        parameters: {
            query?: {
                status?: "pending" | "approved" | "rejected";
                take?: number;
                /** @description 簡易全文検索（メール/電話/氏名など） */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationDto"];
            };
        };
        responses: {
            /** @description 作成された応募のサマリを返す */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ApplicationsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description application not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationsController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 承認後のサマリ＋移行結果＋補完�目 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description application not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationsController_upsertInterviewForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertInterviewFormDto"];
            };
        };
        responses: {
            /** @description 取り込み後の最新を返却 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationsController_createDoc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationDocDto"];
            };
        };
        responses: {
            /** @description 作成（または置き換え）された添付メタ情�を返す */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description application not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationsController_migrateToCast: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CastCodeController_issue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueCastCodeDto"];
            };
        };
        responses: {
            /** @description 採番結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueCastCodeResponseDto"];
                };
            };
            /** @description 不正な userId 等 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 400 */
                        statusCode: number;
                        message: string | string[];
                        /** @example Bad Request */
                        error: string;
                    };
                };
            };
        };
    };
    ShopsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shop のリスト */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopEntity"][];
                };
            };
        };
    };
    ShopsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShopDto"];
            };
        };
        responses: {
            /** @description 作成結果 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopEntity"];
                };
            };
            /** @description フォーマット違反（例: shopNumber が 3–4 桁でない等） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 400 */
                        statusCode: number;
                        message: string | string[];
                        /** @example Bad Request */
                        error: string;
                    };
                };
            };
            /** @description ユニーク制約違反（例: shopNumber 重複） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 400 */
                        statusCode: number;
                        message: string | string[];
                        /** @example Bad Request */
                        error: string;
                    };
                };
            };
        };
    };
    ShopsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shop の詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopEntity"];
                };
            };
            /** @description shop not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 400 */
                        statusCode: number;
                        message: string | string[];
                        /** @example Bad Request */
                        error: string;
                    };
                };
            };
        };
    };
    ShopsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShopDto"];
            };
        };
        responses: {
            /** @description 更新後の店舗 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopEntity"];
                };
            };
            /** @description フォーマット違反（例: shopNumber が 3–4 桁でない等） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 400 */
                        statusCode: number;
                        message: string | string[];
                        /** @example Bad Request */
                        error: string;
                    };
                };
            };
            /** @description shop not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 400 */
                        statusCode: number;
                        message: string | string[];
                        /** @example Bad Request */
                        error: string;
                    };
                };
            };
            /** @description ユニーク制約違反（例: shopNumber 重複） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 400 */
                        statusCode: number;
                        message: string | string[];
                        /** @example Bad Request */
                        error: string;
                    };
                };
            };
        };
    };
    PeopleController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description user_id (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 対象ユーザーのプロフィール */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    PeopleController_updatePartial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description user_id (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 部分更新後のプロフィール */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    LocationsController_list: {
        parameters: {
            query?: {
                /** @description 1ページ件数(1～100) */
                pageSize?: unknown;
                /** @description ページ番号(1～) */
                page?: unknown;
                /** @description 店名などのあいまい検索 */
                q?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 店舗一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
        };
    };
    LocationsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shop ID (UUID v4) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 店舗1件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    LocationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shop ID (UUID v4) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 店舗更新後の情� */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    RequirementsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ショップ要件（1:1） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    RequirementsController_upsert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 要件のUpsert後 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    FixedCastsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 固定配属一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
        };
    };
    FixedCastsController_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 追�後の1件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    FixedCastsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
                castId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AssignmentsController_list: {
        parameters: {
            query?: {
                /** @description 単日指定（互換）YYYY-MM-DD。与えた�合は from/to に展開されます */
                date?: string;
                /** @description 開始時刻の下限（含む・ISO8601） */
                from?: string;
                /** @description 開始時刻の上限（未満・ISO8601） */
                to?: string;
                /** @description ステータス（複数指定可: CSV または ?status=... を複数） */
                status?: ("planned" | "assigned" | "working" | "completed" | "cancelled")[];
                /** @description キャストIDで絞り込み */
                castId?: string;
                /** @description 取得件数（最大200） */
                take?: number;
                /** @description カーソルID（ページング） */
                cursor?: string;
                /** @description 開始時刻の並び� */
                order?: "asc" | "desc";
            };
            header?: never;
            path: {
                shopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description フィルタ・ページング対応の一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: Record<string, never>[];
                        nextCursor?: string | null;
                    };
                };
            };
        };
    };
    AssignmentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssignmentsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
